### ISSUE TITLE
crashes on all attempts to open app

### ISSUE THREAD

**Issue by atm1991** [gstraube/cythara#2]
Moto G5 Plus, Lineage OS 14.1 (Android 7.1.2), ElementalX kernel 1.0.4, device is rooted with magisksu. happy to provide any other info as requested.

**Comment by gstraube** [comment]
Thank you! In version 1.0 the app does not ask for the required permission (microphone access) at runtime which causes it to crash on Android 6.0 or higher -- sorry about that! This is fixed in version 1.1. The update also contains a wider gauge. It should appear soon on F-Droid.

In the meantime, you can grant the permission manually under `Setttings - Apps - "Cythara" - Permissions`:

![settings](https://user-images.githubusercontent.com/4990890/29700257-6cc1a3da-8963-11e7-9f40-14980e963065.png)
