### ISSUE TITLE
Manual mode with hints

### ISSUE THREAD

**Issue by Minkiu** [gstraube/cythara#40]
Hey there!

Thanks for this great application; I was wondering how hard would it be to either implement a manual mode with hints of how much deviated from the tone you are?

For non experienced players (me) sometimes; I find it hard to find the right tune, and spend few minutes going up and down, Guitar Tuna has a useful feature, where it shows you whether you are above or bellow the expected tune.
![image](https://user-images.githubusercontent.com/1800151/92118263-26f7e100-edee-11ea-8866-3a50278345d9.png)
It could be something as simple as showing the +/- number  on top of the ruler/scale?

Thanks,

Best,
Oscar.

PS: Sorry if I used the incorrect words and hope it makes sense; let me know otherwise!

**Comment by gstraube** [comment]
Hi Oscar! Thank you for the feedback and your suggestion! It shouldn't be too hard to implement and I agree with you that it can certainly be helpful. As you suggested, the number could be shown on top of the ruler/scale and perhaps activated by a setting? I'll look into it and will post a couple of screenshots here.

And don't worry, your wording was perfectly clear :-)!

**Comment by gstraube** [comment]
Here are the screenshots:

![Screenshot_20200906-104743_Cythara](https://user-images.githubusercontent.com/4990890/92322771-90b4fc80-f033-11ea-9a55-a1b5d17c50d4.png)
![Screenshot_20200906-104741_Cythara](https://user-images.githubusercontent.com/4990890/92322772-927ec000-f033-11ea-83a8-97db1f742dca.png)
![Screenshot_20200906-110909_Cythara](https://user-images.githubusercontent.com/4990890/92322774-94488380-f033-11ea-8641-3357ea746e55.png)

**Comment by Minkiu** [comment]
Looking great! 

Will you also make it able to specify the string you are tuning?
Maybe when tapping the microphone or from the three dots menu; it can open a "Pop up" menu, like when setting reference pitch, but it would let you choose between Auto and one of the six strings?

i.e I want to tune `A` and it's way off its tune, whith the deviation showing (off-scale), it's easier for me to get closer faster 😄

**Comment by gstraube** [comment]
Not yet, but that's a great idea! I'll look into that.

**Comment by gstraube** [comment]
Here is the APK if you can and want to give it a try. I'd appreciate your feedback!
[cythara.apk.zip](https://github.com/gstraube/cythara/files/5179821/cythara.apk.zip)

The values you can choose from are the notes associated with the strings and not the string number itself (since the tunings itself only contain information about the notes).

I limited the maximum displayed deviation to twice the size of the scale (-120 and 120) because there are some irritating detection results (from overtones?) with a deviation of more than 1000. I'm not sure what values make sense here since the string will presumably go completely slack or snap if it is too much out of tune :-).

![Screenshot_20200906-161317_Cythara](https://user-images.githubusercontent.com/4990890/92328402-c7edd280-f060-11ea-81e9-8bb6dff9ceeb.png)
![Screenshot_20200906-164027_Cythara](https://user-images.githubusercontent.com/4990890/92328404-ce7c4a00-f060-11ea-9c07-5750e3477efa.png)
![Screenshot_20200906-155424_Cythara](https://user-images.githubusercontent.com/4990890/92328406-d0460d80-f060-11ea-87b2-63471e4fff98.png)

**Comment by Minkiu** [comment]
Hey just got around testing it, 

and looking at your screen shot, the apk you provided has a far more extensive list of tones (?) than the common E2, A2, D3, G3, B3, E4 although in your picture it seem to start on the E4, B3 so maybe you already changed it after compiling that apk, just mentioning it.

And a minor thing that would be handy is, whenever you choose something that is not auto, an "AUTO" button could be placed in the dialogue next to the cancel/ok as in to "reset" to auto (I though of this cause the list in my app is way bigger, and having to scroll through it to find AUTO can be annoying, but if the list is going to be only the six strings it's not really that handy :P ), which most people I believe it's what they use, I did a quick mock-up:
![image](https://user-images.githubusercontent.com/1800151/92331257-5ff1b900-f06d-11ea-9397-6e52d45e69be.png)

Cheers!

**Comment by gstraube** [comment]
> and looking at your screen shot, the apk you provided has a far more extensive list of tones (?) than the common E2, A2, D3, G3, B3, E4 although in your picture it seem to start on the E4, B3 so maybe you already changed it after compiling that apk, just mentioning it.

Perhaps you had the tuning set to "Chromatic"? This is the default setting. If you set it to "Guitar (standard)" like in the screenshot, you should only see the notes you mentioned.

> And a minor thing that would be handy is, whenever you choose something that is not auto, an "AUTO" button could be placed in the dialogue next to the cancel/ok as in to "reset" to auto (I though of this cause the list in my app is way bigger, and having to scroll through it to find AUTO can be annoying, but if the list is going to be only the six strings it's not really that handy :P ), which most people I believe it's what they use, I did a quick mock-up:
> ![image](https://user-images.githubusercontent.com/1800151/92331257-5ff1b900-f06d-11ea-9397-6e52d45e69be.png)

Sure, that makes sense! Thanks for the mock-up!

> But tested all the strings and it works as expected! Great work, you are a legend.
Thanks a lot :-D!

**Comment by Minkiu** [comment]
You are right, it's because I had "Chromatic" selected, choosing "Guitar (standard)" does the trick, sorry :upside_down_face: 

Thanks to you, If you have a paypal or similar, I will toss you some coins.

**Comment by gstraube** [comment]
> You are right, it's because I had "Chromatic" selected, choosing "Guitar (standard)" does the trick, sorry upside_down_face

No problem!

> Thanks to you, If you have a paypal or similar, I will toss you some coins.

Interacting with such helpful and nice people as you is more than enough appreciation for me :-)! But thank you!

Here's the version with the button included:

[cythara.apk.zip](https://github.com/gstraube/cythara/files/5183773/cythara.apk.zip)

I noticed that the apparent detection is worse for individual notes compared to auto mode. This is because detection results are sampled and their average published only once the number of samples exceeds a certain (currently hard-coded) size. And there are more detection results in auto mode. I'm thinking of making this configurable before publishing the tuning mode feature.

**Comment by gstraube** [comment]
The sign was missing in the tuning mode lists of note names. It's fixed in this version: 
[cythara.apk.zip](https://github.com/gstraube/cythara/files/5183941/cythara.apk.zip)

**Comment by Minkiu** [comment]
Hey,

Just tested it and works as advertised ;)

I have noticed, even in auto mode, that the string E2 is sometimes finicky, as in it takes a while or you need to be pretty close to the tune for the app to actually register it, not sure if it has to do with what you mention above.

**Comment by gstraube** [comment]
I think it might a combination of multiple things such as the above mentioned sampling size, the instrument, phone, environment noises. For instance, the detection of E2 works reasonably well on my phone but less so for other strings.

If it is okay with you, I would close this issue and have a look at possibly improving detection separately.

**Comment by Minkiu** [comment]
Sure, sorry if I implied otherwise, but the work here is done 👍 
Thanks again.

**Comment by gstraube** [comment]
No worries, you didn't :).

You're very welcome and thank you, too!
