### ISSUE TITLE
notes names

### ISSUE THREAD

**Issue by bderembl** [gstraube/cythara#9]
great app.
woud it be possible to have the option to see the notes in romance language (C=do D=re E=mi, etc), especially for the chromatic tuner which is the most generic tuner?
https://en.wikipedia.org/wiki/Solf%C3%A8ge#Fixed_do_solf%C3%A8ge
thanks!

**Comment by gstraube** [comment]
Thank you! For sure, that's an excellent idea. The app might also automatically preselect the notation based on the device language. The selection can be overridden by the user. Do you think this makes sense?

**Comment by bderembl** [comment]
yes, I think having both options (automatic and user selection) would be perfect

**Comment by gstraube** [comment]
I'm not sure how to specify the octave when displaying note names in Solfège. Is it acceptable to include the octave number that would be used for the same note in scientific pitch notation (https://en.wikipedia.org/wiki/Scientific_pitch_notation) like in this screenshot?

![screenshot_20180107-171124](https://user-images.githubusercontent.com/4990890/34652960-829593dc-f3e5-11e7-911a-c0bfd8848906.png)

**Comment by bderembl** [comment]
It's actually a little more tricky than that: in the french notation (which is the one I am interested in), the octave number is shifted by 1. If it is simpler for you, just keep the scientific notation and add a note somewhere to explain your choice
https://fr.wikipedia.org/wiki/Octave_(musique)#Solf%C3%A8ge

**Comment by gstraube** [comment]
Ah, that's interesting! Thanks a lot! This shouldn't be too big of an adjustment and if understood correctly, the French notation is also used in other countries ("et plus largement dans la notation latine"). Even if this isn't the case, I could add a language specific mapping later when somebody complains :-).

**Comment by bderembl** [comment]
I also noticed that there is no zeroth octave in latin notation (it goes from -1 to 1...)

**Comment by gstraube** [comment]
There is a new release (here and on Google Play) containing support for Solfège. It takes a couple of days for it to be published on F-Droid.

The octave numbering has now been adjusted. I removed the automatic notation selection since locales seem to be a bit messy and I suspect it will not work reliably.

The notation can be chosen via the overflow menu in the toolbar (see screenshots).

Let me know what you think!

![screenshot_20180108-175853](https://user-images.githubusercontent.com/4990890/34682528-6652c112-f49f-11e7-968a-925eb4e26a28.png)
![screenshot_20180108-175847](https://user-images.githubusercontent.com/4990890/34682535-6c72d5b4-f49f-11e7-87d4-dbe0199c5595.png)

**Comment by bderembl** [comment]
thanks! will try the next release on fdroid

**Comment by gstraube** [comment]
It might take a little longer since the F-Droid build tools appear to be unstable at the moment (and builds are failing) but I will leave a comment once it's out there.

**Comment by gstraube** [comment]
The update has been published on F-Droid.

**Comment by bderembl** [comment]
works great! thank you

**Comment by gstraube** [comment]
You're welcome! Thank you for your suggestion and support!
